services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_agent_data:/var/lib/beszel-agent
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      #LISTEN: 45876
      HUB_URL: http://localhost:8090
      #HUB_URL: http://192.168.1.23:8090
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICuD3MFis5N5ILPK3XcFAVdyXvhTlntMkDYAoH2h0SnU'
      TOKEN: 
