services:
  nextcloud-aio-mastercontainer:
    image: ghcr.io/nextcloud/all-in-one:latest
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1 # Or 127.0.0.1 if Traefik is on host
      - NEXTCLOUD_DATADIR=/path/to/your/data # Important, outside webroot
      # You may need to also add - NEXTCLOUD_URL=https://nextcloud.snow-lab.duckdns.org
    networks:
      - proxy

networks:
  proxy:
    external: true

