---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infra:
    - Proxmox:
        href: https://proxmox.snow-lab.duckdns.org
        description: Proxmox instance

- Applications:
    - Immich:
        href: http://immich.snow-lab.duckdns.org
        container: immich
        description: Immich photo library

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
