---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Snow Home Lab
description: Apps and services in my home lab

background:
  image: https://images.unsplash.com/photo-1522726336270-3a0053210f06?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm
  saturate: 75
  brightness: 50
  opacity: 75

theme: dark
color: slate

layout:
  Hypervisors/Virtualization:
    style: row
    columns: 4

  Network/DNS/Proxy:
    style: column
    #style: row
    #columns: 4

  Applications:
    style: column
      #style: row
      #columns: 4

providers:
  openweathermap: "{{HOMEPAGE_VAR_OPEN_WEATHER_API_KEY}}"
  weatherapi: weatherapiapikey

quicklaunch:
  searchDescriptions: true
  #hideInternetSearch: true
  showSearchSuggestions: true
  #hideVisitURL: true
  provider: duckduckgo #google, duckduckgo, bing, baidu, brave or custom
