---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
        timeStyle: short

- openweathermap:
    latitude: "{{HOMEPAGE_VAR_LATITUDE}}"
    longitude: "{{HOMEPAGE_VAR_LONGITUDE}}"
    provider: openweathermap

#- greeting:
#    text_size: xl
#    text: Snow Lab

- logo:
    icon: mdi-snowman-#81d3f2 #D7EBF4

#- unifi_console:
#    #url: https://unifi.ui.com
#    url: https://192.168.1.1/proxy/network/integrations/v1/sites 
    #site: Site Name # optional
    #username: "{{HOMEPAGE_VAR_UNIFI_USERNAME}}"
    #password: "{{HOMEPAGE_VAR_UNIFI_PASSWORD}}"
    #    key: "{{HOMEPAGE_VAR_UNIFI_API_KEY}}" # required if using API key instead of username/password
