volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:

networks:
  proxy:
    external: true
  romm:

services:
  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=${MARIA_DB_HOST}
      - DB_NAME=${MARIA_DB_NAME} # Should match MARIADB_DATABASE in mariadb 
      - DB_USER=${MARIA_DB_USER} # Should match MARIADB_USER in mariadb
      - DB_PASSWD=${MARIA_DB_PASSWORD} # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY=${ROM_AUTH_SECRET_KEY} # Generate a key with `openssl rand -hex 32`
      #- SCREENSCRAPER_USER=${SCREENSCRAPER_USER} # These are the recommended metadata providers
      #- SCREENSCRAPER_PASSWORD=${SCREENSCRAPER_PASSWORD} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#screenscraper
      - RETROACHIEVEMENTS_API_KEY=${RETROACHIEVEMENTS_API_KEY} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#retroachievements
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#steamgriddb
      - HASHEOUS_API_ENABLED=${HASHEOUS_API_ENABLED} # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET}
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /mnt/nfs-share/romm/library:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - /mnt/nfs-share/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - /mnt/nfs-share/romm/config:/romm/config # Path where config.yml is stored
    #ports:
    #  - 88:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.romm.rule=Host(`romm.snow-lab.duckdns.org`)"
      - "traefik.http.routers.romm.entrypoints=http"
      - "traefik.http.middlewares.romm-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.romm.middlewares=romm-https-redirect"
      - "traefik.http.routers.romm-secure.entrypoints=https"
      - "traefik.http.routers.romm-secure.rule=Host(`romm.snow-lab.duckdns.org`)"
      - "traefik.http.routers.romm-secure.tls=true"
      - "traefik.http.routers.romm-secure.service=romm"
      - "traefik.http.services.romm.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"  
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true
    networks:
      - proxy
      - romm

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD} # Use a unique, secure password
      - MARIADB_DATABASE=${MARIA_DB_NAME}
      - MARIADB_USER=${MARIA_DB_USER}
      - MARIADB_PASSWORD=${MARIA_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - romm
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
