networks:
  proxy:
    external: true

services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    #ports:
    #  - 5001:5001
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.snow-lab.duckdns.org`)"
      - "traefik.http.routers.dockge.entrypoints=http"
      - "traefik.http.routers.dockge-secure.tls=true"
      - "traefik.http.services.dockge.loadbalancer.server.scheme=http"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "traefik.http.middlewares.dockge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dockge.middlewares=dockge-https-redirect"
      - "traefik.http.routers.dockge-secure.entrypoints=https"
      - "traefik.http.routers.dockge-secure.rule=Host(`dockge.snow-lab.duckdns.org`)"
      - "traefik.http.routers.dockge-secure.service=dockge"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/kyle-snow/snow-lab-stacks/stacks:/home/kyle-snow/snow-lab-stacks/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/kyle-snow/snow-lab-stacks/stacks
      - PUID=1000
      - PGID=1000
