networks:
  proxy:
    external: true

services:
  portainer:
    container_name: "portainer"
    entrypoint:
      - "/portainer"
    image: "portainer/portainer-ce:lts"

    networks:
      - proxy

    ports:
      - "8000:8000/tcp"
      - "9443:9443/tcp"

    restart: unless-stopped

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

    working_dir: "/"

volumes:
  portainer_data:
    external: true
