networks:
  nginx-proxy-manager_default:
    external: true
    name: nginx-proxy-manager_default
services:
  heimdall:
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: heimdall
    environment:
      - TZ=Etc/UTC
    image: linuxserver/heimdall:latest
    ipc: private
    labels:
      build_version: Linuxserver.io version:- v2.6.3-ls309 Build-date:-
        2025-05-23T18:49:09+00:00
      org.opencontainers.image.source: https://github.com/linuxserver/docker-heimdall
    networks:
      - nginx-proxy-manager_default
    ports:
      - 4433:443/tcp
      - 8080:80/tcp
    restart: unless-stopped
    volumes:
      - 2a3819ccb5e0c739bc2ffdf67df28be52de76f55de84c4c9b361bc3744f41510:/config
volumes:
  2a3819ccb5e0c739bc2ffdf67df28be52de76f55de84c4c9b361bc3744f41510:
    external: true